In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Generate synthetic binary classification data
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

# Split into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# -------------------------------
# 1️⃣ Perceptron (from scratch)
# -------------------------------
class Perceptron:
    def __init__(self, lr=0.01, n_iter=1000):
        self.lr = lr
        self.n_iter = n_iter

    def fit(self, X, y):
        n_samples, n_features = X.shape
        y_ = np.where(y <= 0, -1, 1)
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iter):
            for idx, xi in enumerate(X):
                condition = y_[idx] * (np.dot(xi, self.weights) + self.bias)
                if condition <= 0:
                    self.weights += self.lr * y_[idx] * xi
                    self.bias += self.lr * y_[idx]

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        return np.where(linear_output >= 0, 1, 0)

# -------------------------------
# 2️⃣ Logistic Regression (vectorized)
# -------------------------------
class LogisticRegressionScratch:
    def __init__(self, lr=0.01, n_iter=1000):
        self.lr = lr
        self.n_iter = n_iter

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iter):
            linear_model = np.dot(X, self.weights) + self.bias
            y_predicted = self.sigmoid(linear_model)

            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)

            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_predicted = self.sigmoid(linear_model)
        return np.where(y_predicted >= 0.5, 1, 0)

# -------------------------------
# 3️⃣ Naive Bayes (scikit-learn)
# -------------------------------
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
nb_preds = nb_model.predict(X_val)

# -------------------------------
# Helper: Evaluate and Print Metrics
# -------------------------------
def evaluate_model(name, y_true, y_pred):
    print(f"\n=== {name} ===")
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred))
    print("Recall:", recall_score(y_true, y_pred))
    print("F1 Score:", f1_score(y_true, y_pred))

# -------------------------------
# Run Perceptron
# -------------------------------
perceptron = Perceptron(lr=0.01, n_iter=1000)
perceptron.fit(X_train, y_train)
perceptron_preds = perceptron.predict(X_val)
evaluate_model("Perceptron", y_val, perceptron_preds)

# -------------------------------
# Run Logistic Regression
# -------------------------------
logreg = LogisticRegressionScratch(lr=0.01, n_iter=1000)
logreg.fit(X_train, y_train)
logreg_preds = logreg.predict(X_val)
evaluate_model("Logistic Regression", y_val, logreg_preds)

# -------------------------------
# Run Naive Bayes
# -------------------------------
evaluate_model("Naive Bayes", y_val, nb_preds)



=== Perceptron ===
Confusion Matrix:
 [[65 24]
 [15 96]]
Accuracy: 0.805
Precision: 0.8
Recall: 0.8648648648648649
F1 Score: 0.8311688311688312

=== Logistic Regression ===
Confusion Matrix:
 [[78 11]
 [24 87]]
Accuracy: 0.825
Precision: 0.8877551020408163
Recall: 0.7837837837837838
F1 Score: 0.8325358851674641

=== Naive Bayes ===
Confusion Matrix:
 [[77 12]
 [26 85]]
Accuracy: 0.81
Precision: 0.8762886597938144
Recall: 0.7657657657657657
F1 Score: 0.8173076923076923
